### ISSUE TITLE
bkgMethod Errors

### ISSUE THREAD

**Issue by kglidic** [eas342/tser_tools#18]
The corresponding .yaml file used was attached as a .txt file (will need to be converted back into a .yaml file to test). 
[NRCA1_phot_pipeline.txt](https://github.com/eas342/tshirt/files/6300236/NRCA1_phot_pipeline.txt)

The following background subtraction methods return the following errors when running `do_phot`:

`phot = phot_pipeline.phot(paramFile='/home/kglidic/Software/Pipeline_test/NRCA1_phot_pipeline.yaml')`
`phot.do_phot(useMultiprocessing=False) `

median: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-28-27092f223f3d> in <module>
----> 1 phot.do_phot(useMultiprocessing=False) #extract the photometric data

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in do_phot(self, useMultiprocessing)
   1133             outputPhot = []
   1134             for ind in tqdm.tqdm(fileCountArray):
-> 1135                 outputPhot.append(self.phot_for_one_file(ind))
   1136 
   1137         ## unpack the results

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in phot_for_one_file(self, ind)
    999                     bkg_data = mask.multiply(img)
   1000                     bkg_data_1d = bkg_data[mask.data > 0]
-> 1001                     oneIntensity, oneErr = robust_statistics(bkg_data_1d,method=self.param['bkgMethod'])
   1002                     bkgIntensity.append(oneIntensity)
   1003                     bkgIntensityErr.append(oneErr)

NameError: name 'robust_statistics' is not defined

robust mean:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-31-27092f223f3d> in <module>
----> 1 phot.do_phot(useMultiprocessing=False) #extract the photometric data

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in do_phot(self, useMultiprocessing)
   1133             outputPhot = []
   1134             for ind in tqdm.tqdm(fileCountArray):
-> 1135                 outputPhot.append(self.phot_for_one_file(ind))
   1136 
   1137         ## unpack the results

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in phot_for_one_file(self, ind)
    999                     bkg_data = mask.multiply(img)
   1000                     bkg_data_1d = bkg_data[mask.data > 0]
-> 1001                     oneIntensity, oneErr = robust_statistics(bkg_data_1d,method=self.param['bkgMethod'])
   1002                     bkgIntensity.append(oneIntensity)
   1003                     bkgIntensityErr.append(oneErr)

NameError: name 'robust_statistics' is not defined

colrow:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-27092f223f3d> in <module>
----> 1 phot.do_phot(useMultiprocessing=False) #extract the photometric data

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in do_phot(self, useMultiprocessing)
   1133             outputPhot = []
   1134             for ind in tqdm.tqdm(fileCountArray):
-> 1135                 outputPhot.append(self.phot_for_one_file(ind))
   1136 
   1137         ## unpack the results

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in phot_for_one_file(self, ind)
   1008                 srcPhot = rawPhot['aperture_sum'] - bkgVals
   1009             elif self.param['bkgMethod'] == 'colrow':
-> 1010                 srcPhot, bkgVals, bkgValsErr = self.poly_sub_phot(img,head,err,ind)
   1011             else:
   1012                 raise Exception("Unrecognized background method {}".format(self.param['bkgMethod']))

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in poly_sub_phot(self, img, head, err, ind, showEach, saveFits)
   1107         ## use the error in the mean background as an estimate for error
   1108         bkgPhotTotal = aperture_photometry(img,self.bkgApertures,error=err,method=self.param['subpixelMethod'])
-> 1109         bkgValsErr = bkgPhotTotal['aperture_sum_err'] / self.bkgApertures.area() * self.srcApertures.area()
   1110 
   1111 

TypeError: 'float' object is not callable

**Comment by eas342** [comment]
OK, I think I fixed the robust_statistics errors. I can't re-produce the `colrow` one. Can you try again after git pull?

**Comment by kglidic** [comment]
Seems after git pull the robust_statistics error goes away. However, with every method (other than mean) I get this 'float' error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-27092f223f3d> in <module>
----> 1 phot.do_phot(useMultiprocessing=False) #extract the photometric data

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in do_phot(self, useMultiprocessing)
   1133             outputPhot = []
   1134             for ind in tqdm.tqdm(fileCountArray):
-> 1135                 outputPhot.append(self.phot_for_one_file(ind))
   1136 
   1137         ## unpack the results

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in phot_for_one_file(self, ind)
   1008                 srcPhot = rawPhot['aperture_sum'] - bkgVals
   1009             elif self.param['bkgMethod'] == 'colrow':
-> 1010                 srcPhot, bkgVals, bkgValsErr = self.poly_sub_phot(img,head,err,ind)
   1011             else:
   1012                 raise Exception("Unrecognized background method {}".format(self.param['bkgMethod']))

~/miniconda3/envs/JWST/lib/python3.9/site-packages/tshirt/pipeline/phot_pipeline.py in poly_sub_phot(self, img, head, err, ind, showEach, saveFits)
   1107         ## use the error in the mean background as an estimate for error
   1108         bkgPhotTotal = aperture_photometry(img,self.bkgApertures,error=err,method=self.param['subpixelMethod'])
-> 1109         bkgValsErr = bkgPhotTotal['aperture_sum_err'] / self.bkgApertures.area() * self.srcApertures.area()
   1110 
   1111 

TypeError: 'float' object is not callable

**Comment by eas342** [comment]
OK, it should be fixed now. Thanks for the bug reports!
